# Default application configuration for StockQueryService

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:stockquery;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    br.com.stockqueryservice: INFO