server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto-teste
    driver-class-name: org.postgresql.Driver
    username: projeto-teste
    password: projeto-teste
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    br.com.stockqueryservice: INFO